export const lista_veiculo = [
  {
    nome: 'M4 Sherman',
    pais_origem: 'EUA',
    status: 'Retirado',
    classificacao: 'Veiculo terrestre',
    tipo: 'Blindado medio',
    fabricante: 'American Locomotive Company, Baldwin Locomotive Works, Detroit Tank Arsenal, Federal Machine and Welder Company, Fisher Tank Arsenal, Ford Motor Company, Lima Locomotive Works, Pacific Car and Foundry Company, Pressed Steel Car Company, Pullman-Standard Car Company',
    utilizadores: "Argentina, Australia, Bangladesh, Belgium, Brazil, Canada, Chile, Cuba, Denmark, Egypt, Ethiopia, Free France, France, Greece, India, Iran, Israel, Italy, Indonesia, Japan, Lebanon, Mexico, Nazi Germany, Netherlands, New Zealand, Nicaragua, Pakistan, Paraguay, Peru, Philippines, Poland, Portugal, People's Republic of China, Republic of China, South Africa, South Korea, Soviet Union, Sweden, Syria, Uganda, Turkey, United Kingdom, United States, Yugoslavia",
    variantes: 'M10 tank destroyer, M36 tank destroyer, M7 Priest self-propelled gun, M12 self-propelled gun, M40 self-propelled gun',
    quantidade_produzida: '',
    quantidade_produzida_unidade: '',
    periodo_servico: '',
    massa: '',
    massa_unidade: '',
    comprimento: '',
    comprimento_unidade: '',
    altura: '',
    altura_unidade: '',
    largura: '',
    largura_unidade: '',
    tripulacao: '',
    custo_unitario: '',
    custo_unitario_moeda: '',
    armamento: '',
  },
  {
    nome: 'T-34 76',
    pais_origem: 'URSS',
    tipo: 'Blindado medio',
  }
];